### ISSUE TITLE
SignSaboteur not showing up

### ISSUE THREAD

**Issue by evalihub** [d0ge/sign-saboteur#5]
I have installed the extension from github and install through source. I have used the latest stable and the latest Early adopter versions. Tried on two different machines neither are working.

The tab shows up but it is not detecting the JWT in repeater, HTTP History:

<img width="717" alt="image" src="https://github.com/d0ge/sign-saboteur/assets/117573633/0518ed44-c8a7-4fd5-965d-ae1c98c56eea">

**Comment by BigB86** [comment]
I am also having this same exact issue. I'm on Burp Suite Pro v2024.4.5 and this extension seems completely broken. It's not highlighting anything in proxy history and SignSabeteur tab is missing from proxy intercept as well as repeater. It was unable to pick up express cookie-session middleware token.

**Comment by Themaim** [comment]
go to settings on the app and enable all the tick boxes, seems to make it show up 
![image](https://github.com/d0ge/sign-saboteur/assets/141221448/631c2828-a1d9-412f-b709-3dfcd5480d1f)

**Comment by d0ge** [comment]
Hello @evalihub,
Please make sure that JWT or Nimbusds checkbox is enabled at SignSaboteur -> Settings -> Enabled signers. The extension  supports brute force attack only for HMAC hashes, so JWT setting won't show tokens RS256, ES256 etc.
Please share with me the test token, if you believe that the extension is missing something. Please DO NOT send real tokens, just header part or the part that makes sense.

**Comment by d0ge** [comment]
Hello @BigB86 
Please make sure that Express checkbox is enabled at SignSaboteur -> Settings -> Enabled signers. Take a look on the comment https://github.com/d0ge/sign-saboteur/issues/5#issuecomment-2158716018 kindly added by @Themaim 
Please bear in mind that Express token should be a valid request parameter with following express parameter.sig signature parameter. 
Please share with me the test token, if you believe that the extension is missing something. Please DO NOT send real tokens, just the part that makes sense.
Cheers
