### ISSUE TITLE
Reload the built-in lists

### ISSUE THREAD

**Issue by lanmaster53** [d0ge/sign-saboteur#6]
I accidentally cleared the builtin list of secrets and cannot figure out how to repopulate them. There doesn't seem to be anything in the interface to reload them, and I've tried unloading and reloading, and uninstalling and reinstalling the extension, but neither of these approaches work.

**Comment by okiokpentest1** [comment]
same here

**Comment by d0ge** [comment]
Hello @lanmaster53,

Thank you for raising the issue! We've introduced two new buttons in the UI on [this branch](https://github.com/d0ge/sign-saboteur/tree/6-reload-the-built-in-lists), which will allow you to easily restore the default secrets.

While this feature is not yet deployed, you can manually download the default secrets from the [resources folder](https://github.com/d0ge/sign-saboteur/blob/main/src/main/resources/secrets). This should help resolve the issue for now.

Cheers,
Cheers
